-- 01-ddl.sql — absences (absence requests): a state-machine entity with soft-delete.

CREATE TABLE hr_absences (
    absence_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    employee_no      VARCHAR2(20)  NOT NULL,
    absence_type     VARCHAR2(30)  NOT NULL,
    date_from        DATE          NOT NULL,
    date_to          DATE          NOT NULL,
    status           VARCHAR2(20)  DEFAULT 'REQUESTED' NOT NULL,
    rejection_reason VARCHAR2(400),
    approved_by      VARCHAR2(60),
    approved_at      TIMESTAMP,
    cancelled_at     TIMESTAMP,                 -- soft-delete via audit columns (§6)
    cancelled_by     VARCHAR2(60),
    cancel_reason    VARCHAR2(400),
    CONSTRAINT hr_absences_pk PRIMARY KEY (absence_id),
    CONSTRAINT hr_absences_status_ck CHECK (status IN ('REQUESTED','APPROVED','REJECTED')),
    CONSTRAINT hr_absences_dates_ck CHECK (date_to >= date_from)
);

-- Seed: one REQUESTED (transitionable) and one already APPROVED (for the illegal-transition path).
INSERT INTO hr_absences (employee_no, absence_type, date_from, date_to)
VALUES ('1001', 'VACATION', DATE '2026-07-01', DATE '2026-07-10');
INSERT INTO hr_absences (employee_no, absence_type, date_from, date_to, status, approved_by, approved_at)
VALUES ('1002', 'SICK_LEAVE', DATE '2026-06-20', DATE '2026-06-22', 'APPROVED', 'ADMIN', SYSTIMESTAMP);
COMMIT;
