-- 01-ddl.sql — employee master: table + integrity backstops + seed.
-- Depends on hr_sectors (see ../sectors-catalog/01-ddl.sql): the FK is what makes
-- "the sector must be active" a real rule instead of a demo.

CREATE TABLE hr_employees (
    employee_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    full_name    VARCHAR2(120) NOT NULL,
    email        VARCHAR2(150) NOT NULL,
    sector_id    NUMBER        NOT NULL,
    hired_on     DATE          DEFAULT TRUNC(SYSDATE) NOT NULL,
    active_flag  VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    row_version  NUMBER        DEFAULT 1 NOT NULL,   -- lost-update guard, section 7
    CONSTRAINT hr_employees_pk PRIMARY KEY (employee_id),
    CONSTRAINT hr_employees_sector_fk FOREIGN KEY (sector_id)
        REFERENCES hr_sectors (sector_id),
    CONSTRAINT hr_employees_active_ck CHECK (active_flag IN ('Y','N'))
);

-- Race backstop for the package's check-then-insert uniqueness (case-insensitive).
-- The package check gives the friendly message; this index guarantees correctness.
CREATE UNIQUE INDEX hr_employees_email_uq ON hr_employees (UPPER(email));

-- Seed: one existing employee so the rejection path (duplicate email) has a collision.
INSERT INTO hr_employees (full_name, email, sector_id)
SELECT 'Ana Rojas', 'ana.rojas@example.com', sector_id FROM hr_sectors WHERE code = 'PROD';
COMMIT;
