-- 01-ddl.sql — sectors catalog: table + integrity backstops + seed.

CREATE TABLE hr_sectors (
    sector_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    code         VARCHAR2(30)  NOT NULL,
    name         VARCHAR2(100) NOT NULL,
    active_flag  VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    CONSTRAINT hr_sectors_pk PRIMARY KEY (sector_id),
    CONSTRAINT hr_sectors_active_ck CHECK (active_flag IN ('Y','N'))
);

-- Race backstop for the package's check-then-insert uniqueness (case-insensitive).
-- The package check gives the friendly message; this index guarantees correctness.
CREATE UNIQUE INDEX hr_sectors_code_uq ON hr_sectors (UPPER(code));

-- Seed: existing codes so the rejection path (duplicate) has something to collide with.
INSERT INTO hr_sectors (code, name) VALUES ('PROD', 'Production');
INSERT INTO hr_sectors (code, name) VALUES ('ADM',  'Administration');
COMMIT;
